#!/usr/bin/env sh

##############################################################################
##
##  Stop and kill currently running docker image, pull newest version and
##  run it.
##
##############################################################################

warn ( ) {
    echo "$*"
}

warn "Currently running docker images"
docker ps -a

warn "Killing currently running docker image..."
docker kill pocket-square-ingest; docker rm pocket-square-ingest

warn "Pulling latest docker image..."
docker pull pocketsquare/pocket-square-ingest:latest

warn "Starting docker image..."
docker run -dit --name pocket-square-ingest --link pocket-square-users -e POCKET_APP_KEY=$POCKET_APP_KEY -p 28102:5000 pocketsquare/pocket-square-ingest:latest

warn "Currently running docker images"
docker ps -a
